// flow-typed signature: 50ccc493fe42484a13abc4014173d059
// flow-typed version: <<STUB>>/css-modules-require-hook_v^4.0.6/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-modules-require-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-modules-require-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-modules-require-hook/lib/attachHook' {
  declare module.exports: any;
}

declare module 'css-modules-require-hook/lib/index' {
  declare module.exports: any;
}

declare module 'css-modules-require-hook/lib/transformTokens' {
  declare module.exports: any;
}

declare module 'css-modules-require-hook/lib/validate' {
  declare module.exports: any;
}

declare module 'css-modules-require-hook/preset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-modules-require-hook/lib/attachHook.js' {
  declare module.exports: $Exports<'css-modules-require-hook/lib/attachHook'>;
}
declare module 'css-modules-require-hook/lib/index.js' {
  declare module.exports: $Exports<'css-modules-require-hook/lib/index'>;
}
declare module 'css-modules-require-hook/lib/transformTokens.js' {
  declare module.exports: $Exports<'css-modules-require-hook/lib/transformTokens'>;
}
declare module 'css-modules-require-hook/lib/validate.js' {
  declare module.exports: $Exports<'css-modules-require-hook/lib/validate'>;
}
declare module 'css-modules-require-hook/preset.js' {
  declare module.exports: $Exports<'css-modules-require-hook/preset'>;
}
