// flow-typed signature: fcccb6d02e56b795f9f2359dccfb444c
// flow-typed version: <<STUB>>/node-mocks-http_v^1.6.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-mocks-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-mocks-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-mocks-http/examples/express-route' {
  declare module.exports: any;
}

declare module 'node-mocks-http/examples/express-status-vs-json' {
  declare module.exports: any;
}

declare module 'node-mocks-http/gulpfile' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/mock-application' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/mock-express' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/mock-request' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/utils/define-getter' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/http-mock' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockEventEmitter' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockRequest' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockResponse' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockWritableStream' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/node/_http_incoming' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/node/_http_server' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/node/http' {
  declare module.exports: any;
}

declare module 'node-mocks-http/test/lib/http-mock.spec' {
  declare module.exports: any;
}

declare module 'node-mocks-http/test/lib/mockEventEmitter.spec' {
  declare module.exports: any;
}

declare module 'node-mocks-http/test/lib/mockRequest.spec' {
  declare module.exports: any;
}

declare module 'node-mocks-http/test/lib/mockResponse.spec' {
  declare module.exports: any;
}

declare module 'node-mocks-http/test/lib/mockWritableStream.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-mocks-http/examples/express-route.js' {
  declare module.exports: $Exports<'node-mocks-http/examples/express-route'>;
}
declare module 'node-mocks-http/examples/express-status-vs-json.js' {
  declare module.exports: $Exports<'node-mocks-http/examples/express-status-vs-json'>;
}
declare module 'node-mocks-http/gulpfile.js' {
  declare module.exports: $Exports<'node-mocks-http/gulpfile'>;
}
declare module 'node-mocks-http/lib/express/mock-application.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/mock-application'>;
}
declare module 'node-mocks-http/lib/express/mock-express.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/mock-express'>;
}
declare module 'node-mocks-http/lib/express/mock-request.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/mock-request'>;
}
declare module 'node-mocks-http/lib/express/utils/define-getter.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/utils/define-getter'>;
}
declare module 'node-mocks-http/lib/http-mock.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/http-mock'>;
}
declare module 'node-mocks-http/lib/mockEventEmitter.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockEventEmitter'>;
}
declare module 'node-mocks-http/lib/mockRequest.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockRequest'>;
}
declare module 'node-mocks-http/lib/mockResponse.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockResponse'>;
}
declare module 'node-mocks-http/lib/mockWritableStream.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockWritableStream'>;
}
declare module 'node-mocks-http/lib/node/_http_incoming.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/node/_http_incoming'>;
}
declare module 'node-mocks-http/lib/node/_http_server.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/node/_http_server'>;
}
declare module 'node-mocks-http/lib/node/http.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/node/http'>;
}
declare module 'node-mocks-http/test/lib/http-mock.spec.js' {
  declare module.exports: $Exports<'node-mocks-http/test/lib/http-mock.spec'>;
}
declare module 'node-mocks-http/test/lib/mockEventEmitter.spec.js' {
  declare module.exports: $Exports<'node-mocks-http/test/lib/mockEventEmitter.spec'>;
}
declare module 'node-mocks-http/test/lib/mockRequest.spec.js' {
  declare module.exports: $Exports<'node-mocks-http/test/lib/mockRequest.spec'>;
}
declare module 'node-mocks-http/test/lib/mockResponse.spec.js' {
  declare module.exports: $Exports<'node-mocks-http/test/lib/mockResponse.spec'>;
}
declare module 'node-mocks-http/test/lib/mockWritableStream.spec.js' {
  declare module.exports: $Exports<'node-mocks-http/test/lib/mockWritableStream.spec'>;
}
