// flow-typed signature: 977f49e4c57a9683d872ad3075fdbaca
// flow-typed version: <<STUB>>/node-hook-filename_v^0.3.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-hook-filename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-hook-filename' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-hook-filename/test/fixtures/configjson' {
  declare module.exports: any;
}

declare module 'node-hook-filename/test/fixtures/test' {
  declare module.exports: any;
}

declare module 'node-hook-filename/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-hook-filename/index' {
  declare module.exports: $Exports<'node-hook-filename'>;
}
declare module 'node-hook-filename/index.js' {
  declare module.exports: $Exports<'node-hook-filename'>;
}
declare module 'node-hook-filename/test/fixtures/configjson.js' {
  declare module.exports: $Exports<'node-hook-filename/test/fixtures/configjson'>;
}
declare module 'node-hook-filename/test/fixtures/test.js' {
  declare module.exports: $Exports<'node-hook-filename/test/fixtures/test'>;
}
declare module 'node-hook-filename/test/index.spec.js' {
  declare module.exports: $Exports<'node-hook-filename/test/index.spec'>;
}
