// flow-typed signature: cfbde02b1162e5337b644785585ed049
// flow-typed version: <<STUB>>/react-bem-helper_v^1.3.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bem-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bem-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bem-helper/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bem-helper/index' {
  declare module.exports: $Exports<'react-bem-helper'>;
}
declare module 'react-bem-helper/index.js' {
  declare module.exports: $Exports<'react-bem-helper'>;
}
declare module 'react-bem-helper/tests.js' {
  declare module.exports: $Exports<'react-bem-helper/tests'>;
}
