// flow-typed signature: ca43cfab81a387fb83c5cfdd217839d4
// flow-typed version: <<STUB>>/redux-via-socket.io_v~0.3.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-via-socket.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-via-socket.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-via-socket.io/lib/client' {
  declare module.exports: any;
}

declare module 'redux-via-socket.io/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-via-socket.io/lib/index' {
  declare module.exports: any;
}

declare module 'redux-via-socket.io/lib/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-via-socket.io/lib/client.js' {
  declare module.exports: $Exports<'redux-via-socket.io/lib/client'>;
}
declare module 'redux-via-socket.io/lib/constants.js' {
  declare module.exports: $Exports<'redux-via-socket.io/lib/constants'>;
}
declare module 'redux-via-socket.io/lib/index.js' {
  declare module.exports: $Exports<'redux-via-socket.io/lib/index'>;
}
declare module 'redux-via-socket.io/lib/server.js' {
  declare module.exports: $Exports<'redux-via-socket.io/lib/server'>;
}
