// flow-typed signature: f6eb6bcb5af51636b8d3d14d0ba427e6
// flow-typed version: <<STUB>>/redux-promise-middleware_v^2.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise-middleware/dist/index' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/actions/post' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/client' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/constants/post' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/reducers/defaultState' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/reducers/posts' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/server' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/store' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/utils/buildURL' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/utils/middleware/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/utils/middleware/promise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/utils/request' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/utils/resources/post' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/utils/server' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/views/home/container' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/views/home/index' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/views/home/view' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/example/webpack.local.config' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise-middleware/dist/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/index'>;
}
declare module 'redux-promise-middleware/dist/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/isPromise'>;
}
declare module 'redux-promise-middleware/example/actions/post.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/actions/post'>;
}
declare module 'redux-promise-middleware/example/client.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/client'>;
}
declare module 'redux-promise-middleware/example/constants/post.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/constants/post'>;
}
declare module 'redux-promise-middleware/example/reducers/defaultState.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/reducers/defaultState'>;
}
declare module 'redux-promise-middleware/example/reducers/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/reducers/index'>;
}
declare module 'redux-promise-middleware/example/reducers/posts.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/reducers/posts'>;
}
declare module 'redux-promise-middleware/example/server.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/server'>;
}
declare module 'redux-promise-middleware/example/store.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/store'>;
}
declare module 'redux-promise-middleware/example/utils/buildURL.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/utils/buildURL'>;
}
declare module 'redux-promise-middleware/example/utils/middleware/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/utils/middleware/isPromise'>;
}
declare module 'redux-promise-middleware/example/utils/middleware/promise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/utils/middleware/promise'>;
}
declare module 'redux-promise-middleware/example/utils/request.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/utils/request'>;
}
declare module 'redux-promise-middleware/example/utils/resources/post.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/utils/resources/post'>;
}
declare module 'redux-promise-middleware/example/utils/server.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/utils/server'>;
}
declare module 'redux-promise-middleware/example/views/home/container.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/views/home/container'>;
}
declare module 'redux-promise-middleware/example/views/home/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/views/home/index'>;
}
declare module 'redux-promise-middleware/example/views/home/view.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/views/home/view'>;
}
declare module 'redux-promise-middleware/example/webpack.local.config.js' {
  declare module.exports: $Exports<'redux-promise-middleware/example/webpack.local.config'>;
}
declare module 'redux-promise-middleware/test/index.spec.js' {
  declare module.exports: $Exports<'redux-promise-middleware/test/index.spec'>;
}
