// flow-typed signature: 0356a688eb193ada422874c79f8b447b
// flow-typed version: <<STUB>>/skin-deep_v^1.0.0-alpha2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'skin-deep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'skin-deep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'skin-deep/chai' {
  declare module.exports: any;
}

declare module 'skin-deep/lib/traversal' {
  declare module.exports: any;
}

declare module 'skin-deep/skin-deep' {
  declare module.exports: any;
}

declare module 'skin-deep/test/chai' {
  declare module.exports: any;
}

declare module 'skin-deep/test/new' {
  declare module.exports: any;
}

declare module 'skin-deep/test/test' {
  declare module.exports: any;
}

declare module 'skin-deep/test/traversal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'skin-deep/chai.js' {
  declare module.exports: $Exports<'skin-deep/chai'>;
}
declare module 'skin-deep/lib/traversal.js' {
  declare module.exports: $Exports<'skin-deep/lib/traversal'>;
}
declare module 'skin-deep/skin-deep.js' {
  declare module.exports: $Exports<'skin-deep/skin-deep'>;
}
declare module 'skin-deep/test/chai.js' {
  declare module.exports: $Exports<'skin-deep/test/chai'>;
}
declare module 'skin-deep/test/new.js' {
  declare module.exports: $Exports<'skin-deep/test/new'>;
}
declare module 'skin-deep/test/test.js' {
  declare module.exports: $Exports<'skin-deep/test/test'>;
}
declare module 'skin-deep/test/traversal.js' {
  declare module.exports: $Exports<'skin-deep/test/traversal'>;
}
